import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { App } from '../src/App';
import { AccountPage } from '../src/pages/Account/AccountPage';
import { apiClient } from '../src/services/api-client';
import { authStorage } from '../src/services/auth-storage';

const user = { id: 'u1', name: 'Lan Nguyễn', email: 'lan@example.test', role: 'admin' as const, emailVerified: true };
const conversation = { id: 'c1', title: 'Hội thoại đã lưu', updatedAt: '2026-10-09T00:00:00Z' };
beforeEach(() => {
  authStorage.setStoredTokens({ accessToken: 'access', refreshToken: 'refresh', user });
  vi.spyOn(apiClient, 'getMe').mockResolvedValue({ user });
  vi.spyOn(apiClient, 'getAuthConfig').mockResolvedValue({ signupEnabled: false, googleEnabled: true });
  vi.spyOn(apiClient, 'getAccount').mockResolvedValue({ account: { ...user, createdAt: '2026-10-01', hasPassword: true, hasGoogle: true, googleEmail: user.email } });
  vi.spyOn(apiClient, 'getAccountSessions').mockResolvedValue({ sessions: [] });
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); authStorage.clearStoredTokens(); });
it('ports the Account page without the shell or demo controls and requires current password in the Google modal', async () => {
  window.history.replaceState({}, '', '/account');
  const unlink = vi.spyOn(apiClient, 'unlinkGoogle').mockResolvedValue({ success: true });
  render(<App />);
  expect(await screen.findByRole('heading', { name: 'Cài đặt tài khoản' })).toBeInTheDocument();
  expect(document.documentElement.dataset.protoPage).toBe('account');
  expect(screen.queryByText(/Kịch bản demo/)).toBeNull();
  fireEvent.click(screen.getByRole('button', { name: 'Gỡ liên kết Google' }));
  const modal = screen.getByRole('dialog');
  fireEvent.click(within(modal).getByRole('button', { name: /Xác nhận gỡ/ }));
  expect(unlink).not.toHaveBeenCalled();
  fireEvent.change(within(modal).getByLabelText(/Mật khẩu hiện tại/), { target: { value: 'Current!password' } });
  fireEvent.click(within(modal).getByRole('button', { name: /Xác nhận gỡ/ }));
  await waitFor(() => expect(unlink).toHaveBeenCalledWith('Current!password'));
});
it('preserves a nonempty legacy whitespace password when confirming Google unlink', async () => {
  window.history.replaceState({}, '', '/account');
  const password = ' '.repeat(12);
  const unlink = vi.spyOn(apiClient, 'unlinkGoogle').mockResolvedValue({ success: true });
  render(<App />);
  fireEvent.click(await screen.findByRole('button', { name: 'Gỡ liên kết Google' }));
  fireEvent.change(within(screen.getByRole('dialog')).getByLabelText(/Mật khẩu hiện tại/), { target: { value: password } });
  fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Xác nhận gỡ' }));
  await waitFor(() => expect(unlink).toHaveBeenCalledWith(password));
});
it('uses the source avatar classes and styled keyboard menu on the Account page', async () => {
  window.history.replaceState({}, '', '/account');
  render(<App />);
  const avatar = await screen.findByRole('button', { name: 'Menu người dùng: Lan Nguyễn' });
  expect(avatar).toHaveClass('w-8', 'h-8', 'rounded-full', 'bg-[#FF5701]', 'text-white', 'text-xs', 'font-bold');
  fireEvent.keyDown(avatar, { key: 'ArrowDown' });
  const first = screen.getByRole('menuitem', { name: 'Nhật ký điều phối' });
  expect(first).toHaveClass('w-full', 'text-left', 'px-4', 'py-2', 'text-xs');
  expect(first).toHaveFocus();
  fireEvent.keyDown(first, { key: 'End' });
  expect(screen.getByRole('menuitem', { name: 'Đăng xuất' })).toHaveFocus();
  fireEvent.keyDown(screen.getByRole('menuitem', { name: 'Đăng xuất' }), { key: 'Escape' });
  expect(screen.queryByRole('menu')).toBeNull(); expect(avatar).toHaveFocus();
});
it('disables approval for an unverified account without reject or invite actions', async () => {
  window.history.replaceState({}, '', '/admin/users');
  vi.spyOn(apiClient, 'getAdminUsers').mockResolvedValue({ users: [{ ...user, id: 'p1', name: 'Chờ xác minh', email: 'pending@example.test', role: 'member', status: 'pending', emailVerified: false, hasPassword: true, hasGoogle: false, createdAt: '2026-10-01', openSessions: 0 }], total: 1, pendingCount: 1, page: 1, limit: 20 });
  render(<App />);
  expect(await screen.findByRole('button', { name: /Duyệt & kích hoạt/ })).toBeDisabled();
  expect(screen.getByText('Người này cần bấm link xác minh trong email trước.')).toBeInTheDocument();
  expect(screen.queryByRole('button', { name: /Từ chối|Mời/ })).toBeNull();
  expect(document.documentElement.dataset.protoPage).toBe('users');
});
it('omits unsupported role filtering and pages actual active/disabled rows without claiming a fixed row count', async () => {
  window.history.replaceState({}, '', '/admin/users');
  vi.spyOn(apiClient, 'getAdminUsers').mockImplementation(async options => {
    const status = options?.status ?? 'active', page = options?.page ?? 1, limit = options?.limit ?? 20;
    const total = status === 'pending' ? 0 : 21;
    const count = status === 'pending' ? 0 : Math.min(limit, page === 1 ? 20 : 1);
    return { users: Array.from({ length: count }, (_, index) => ({ ...user, id: `${status}-${page}-${index}`, name: `${status} ${page}-${index}`, role: 'member' as const, status, emailVerified: true, hasPassword: true, hasGoogle: false, createdAt: '2026-10-01', openSessions: 0 })), total, pendingCount: 0, page, limit };
  });
  render(<App />);
  fireEvent.click(await screen.findByRole('tab', { name: /Thành viên/ }));
  await waitFor(() => expect(document.querySelector('#table-members-body')?.children).toHaveLength(40));
  expect(screen.queryByLabelText('Lọc theo vai trò')).toBeNull();
  expect(screen.getByText('42', { selector: '#stat-total-members' })).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Trang sau' }));
  await waitFor(() => expect(document.querySelector('#table-members-body')?.children).toHaveLength(2));
  expect(screen.getByText('Trang 2')).toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Trang sau' })).toBeDisabled();
});
it('loads own history by title and cursor, opens the saved route, and preserves a newer rename draft after a late save', async () => {
  window.history.replaceState({}, '', '/history');
  const list = vi.spyOn(apiClient, 'getConversations').mockResolvedValue({ conversations: [conversation], nextCursor: 'cursor-1' });
  let resolveRename!: (value: any) => void;
  const rename = vi.spyOn(apiClient, 'renameConversation').mockImplementation(() => new Promise(resolve => { resolveRename = resolve; }));
  render(<App />);
  expect(await screen.findByRole('heading', { name: conversation.title })).toBeInTheDocument();
  expect(document.documentElement.dataset.protoPage).toBe('history');
  expect(screen.queryByText(/Toàn bộ nhóm|Xem biên nhận|Lọc theo trạng thái/)).toBeNull();
  fireEvent.click(screen.getByRole('button', { name: 'Tải thêm' }));
  await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ cursor: 'cursor-1' })));
  fireEvent.click(screen.getByRole('button', { name: /Đổi tên/ }));
  let input = screen.getByRole('textbox', { name: 'Tiêu đề hội thoại' });
  fireEvent.change(input, { target: { value: 'Tên gửi A' } });
  fireEvent.keyDown(input, { key: 'Enter' });
  await waitFor(() => expect(rename).toHaveBeenCalledWith('c1', 'Tên gửi A'));
  fireEvent.change(input, { target: { value: 'Draft B' } });
  await act(async () => resolveRename({ conversation: { ...conversation, title: 'Tên gửi A' } }));
  expect(screen.getByRole('textbox', { name: 'Tiêu đề hội thoại' })).toHaveValue('Draft B');
  input.focus();
  fireEvent.keyDown(input, { key: 'Escape' });
  expect(screen.queryByRole('textbox', { name: 'Tiêu đề hội thoại' })).toBeNull();
  expect(screen.getByRole('heading', { name: 'Tên gửi A' })).toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Đổi tên Tên gửi A' })).toHaveFocus();
  expect(screen.getByRole('link', { name: 'Mở hội thoại' })).toHaveAttribute('href', '/c/c1');
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'Tiêu đề' } });
  await waitFor(() => expect(list).toHaveBeenLastCalledWith(expect.objectContaining({ search: 'Tiêu đề', cursor: undefined })));
});
it('shows the API email-configuration 503 and leaves the candidate pending without a success notice', async () => {
  window.history.replaceState({}, '', '/admin/users');
  const candidate = { ...user, id: 'p1', name: 'Candidate', email: 'candidate@example.test', role: 'member' as const, status: 'pending' as const, emailVerified: true, hasPassword: true, hasGoogle: false, createdAt: '2026-10-01', openSessions: 0 };
  vi.spyOn(apiClient, 'getAdminUsers').mockResolvedValue({ users: [candidate], total: 1, pendingCount: 1, page: 1, limit: 20 });
  vi.spyOn(apiClient, 'changeAdminUser').mockRejectedValue(Object.assign(new Error('Chưa cấu hình email thông báo duyệt tài khoản.'), { status: 503, data: { code: 'APPROVAL_EMAIL_UNAVAILABLE', error: 'Chưa cấu hình email thông báo duyệt tài khoản.' } }));
  render(<App />);
  fireEvent.click(await screen.findByRole('button', { name: /Duyệt & kích hoạt/ }));
  fireEvent.click(screen.getByRole('button', { name: /Xác nhận duyệt/ }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Chưa cấu hình email thông báo duyệt tài khoản.');
  expect(screen.getByRole('dialog')).toBeInTheDocument();
  expect(document.querySelector('#pending-list-container')).toHaveTextContent(candidate.email);
  expect(screen.queryByText('Đã duyệt. Hệ thống gửi email báo cho người dùng.')).toBeNull();
});
it('releases saving after a search changes while an older rename response is pending', async () => {
  window.history.replaceState({}, '', '/history');
  vi.spyOn(apiClient, 'getConversations').mockResolvedValue({ conversations: [conversation] });
  let finish!: (value: any) => void;
  vi.spyOn(apiClient, 'renameConversation').mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  render(<App />);
  fireEvent.click(await screen.findByRole('button', { name: /Đổi tên/ }));
  fireEvent.change(screen.getByRole('textbox', { name: 'Tiêu đề hội thoại' }), { target: { value: 'Old request' } });
  fireEvent.keyDown(screen.getByRole('textbox', { name: 'Tiêu đề hội thoại' }), { key: 'Enter' });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'Changed search' } });
  fireEvent.click(await screen.findByRole('button', { name: /Đổi tên/ }));
  await act(async () => finish({ conversation: { ...conversation, title: 'Old request' } }));
  expect(screen.getByRole('button', { name: 'Lưu' })).toBeEnabled();
  expect(screen.getByRole('textbox', { name: 'Tiêu đề hội thoại' })).toHaveValue(conversation.title);
});
it('shows the supported fallback for a conversation whose title is not yet set', async () => {
  window.history.replaceState({}, '', '/history');
  vi.spyOn(apiClient, 'getConversations').mockResolvedValue({ conversations: [{ ...conversation, title: null }] });
  vi.spyOn(apiClient, 'renameConversation').mockResolvedValue({ conversation });
  render(<App />);
  expect(await screen.findByRole('heading', { name: 'Hội thoại mới' })).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Đổi tên Hội thoại mới' }));
  const input = screen.getByRole('textbox', { name: 'Tiêu đề hội thoại' });
  input.focus(); fireEvent.change(input, { target: { value: conversation.title } });
  fireEvent.keyDown(input, { key: 'Enter' });
  await waitFor(() => expect(screen.getByRole('button', { name: `Đổi tên ${conversation.title}` })).toHaveFocus());
});
it('releases the account action lock after a user change while an older name save is pending', async () => {
  let finish!: (value: any) => void;
  vi.spyOn(apiClient, 'updateAccountName').mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  const props = { navigate: vi.fn(), onLogout: vi.fn() };
  const view = render(<AccountPage {...props} user={user} />);
  fireEvent.change(await screen.findByLabelText(/Họ và tên/), { target: { value: 'Old name request' } });
  fireEvent.click(screen.getByRole('button', { name: 'Lưu thay đổi họ tên' }));
  const next = { ...user, id: 'u2', name: 'Other User' };
  authStorage.setStoredTokens({ accessToken: 'next', refreshToken: 'next', user: next });
  view.rerender(<AccountPage {...props} user={next} />);
  await act(async () => finish({ user: { ...user, name: 'Old name request' } }));
  expect(screen.getByRole('button', { name: 'Lưu thay đổi họ tên' })).toBeEnabled();
  expect(authStorage.getStoredTokens().user?.id).toBe('u2');
});
