import { randomUUID, createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { EventEmitter } from 'node:events';
import pg from 'pg';
import request from 'supertest';
import { afterAll, beforeAll, expect, it } from 'vitest';
import { AIPlanner, MockLLMProvider } from '@wap/planner';
import { TRELLO_TOOLS } from '@wap/tool-schemas';
import { ChatService } from '../../src/services/chat-service.js';
import { PlanRepo } from '../../src/db/repositories/plan-repo.js';
import { ConversationRepo } from '../../src/db/repositories/conversation-repo.js';
import { MessageRepo } from '../../src/db/repositories/message-repo.js';
import { StepRepo } from '../../src/db/repositories/step-repo.js';
import { ExecutionService } from '../../src/services/execution-service.js';
import { createApp } from '../../src/app.js';
import { generateTokens } from '../../src/auth/jwt.js';
const schema = `fe03_labels_${randomUUID().replaceAll('-', '')}`;
const admin = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, options: `-c search_path=${schema},public` });
beforeAll(async () => {
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL required for FE-03 persistence evidence');
  await admin.query(`CREATE SCHEMA ${schema}`);
  for (const file of ['0001_v3_core.sql', '0004_conversation_titles.sql', '0006_fe03_resource_labels.sql']) await pool.query(await readFile(new URL(`../../../../db/v3/${file}`, import.meta.url), 'utf8'));
});
afterAll(async () => { await pool.end(); await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`); await admin.end(); });
it('real planner lookups -> SSE -> PostgreSQL -> new repositories/HTTP reload preserve display names and immutable hash', async () => {
  const owner = randomUUID();
  await pool.query('INSERT INTO users(id,email,password,name) VALUES($1,$2,$3,$4)', [owner, `${owner}@example.test`, 'test', 'Owner']);
  const convRepo = new ConversationRepo(pool), msgRepo = new MessageRepo(pool), plans = new PlanRepo(pool);
  const conv = await convRepo.createConversation(owner);
  const plan = { kind: 'plan', summary: 'Tạo thẻ', thinking: 'Dùng danh sách đã tra cứu.', warnings: [], steps: [{ id: 'step_1', tool: 'trello.create_card', description: 'Tạo thẻ', args: { listId: 'L1', title: 'B1' }, dependsOn: [] }] };
  const provider = new MockLLMProvider(); provider.setPlanResponses([plan]);
  const planner = new AIPlanner({ provider, toolCatalog: TRELLO_TOOLS, gatherSearch: async ({ tool }) => tool === 'trello.search_boards' ? [{ id: 'B1', name: 'Frontend' }] : [{ id: 'L1', name: 'Cần làm', boardId: 'B1' }] });
  const events = new EventEmitter(); events.on('error', () => {});
  const chat = new ChatService({ convRepo, msgRepo, planRepo: plans, planner, eventEmitter: { emit: (event, data) => events.emit(event, data) } });
  const preview = new Promise<any>((resolve, reject) => { events.once('plan_preview', resolve); events.once('error', reject); events.once('clarification', reject); });
  const accepted = await chat.handleUserMessage({ conversationId: conv.id, userId: owner, content: 'Tạo thẻ trên board Frontend list Cần làm', requestId: 'fe03-sql-request' });
  const event = await preview;
  expect(event.resourceLabels).toEqual({ L1: 'Cần làm (board Frontend)' });
  expect(event).toMatchObject({ replyToMessageId: accepted.messageId, requestId: 'fe03-sql-request' });
  const saved = await new PlanRepo(pool).getPlan(event.planId);
  expect(saved?.resource_labels).toEqual(event.resourceLabels);
  expect(saved?.plan_text).toBe(JSON.stringify(plan));
  expect(saved?.plan_hash).toBe(createHash('sha256').update(JSON.stringify(plan)).digest('hex'));
  const secret = 'fe03-persistence-test-only-secret';
  const headers = { Authorization: `Bearer ${generateTokens({ id: owner, email: `${owner}@example.test`, name: 'Owner' }, secret).accessToken}` };
  const execution = new ExecutionService({ planRepo: new PlanRepo(pool), convRepo: new ConversationRepo(pool), stepRepo: new StepRepo(pool), adapterFactory: {} as any });
  const app = createApp({ jwtSecret: secret, convRepo: new ConversationRepo(pool), msgRepo: new MessageRepo(pool), planRepo: new PlanRepo(pool), chatService: chat, executionService: execution });
  const pending = await request(app).get(`/api/conversations/${conv.id}/plans/active`).set(headers);
  expect(pending.status).toBe(200); expect(pending.body.resourceLabels).toEqual(event.resourceLabels);
  const history = (await request(app).get(`/api/conversations/${conv.id}`).set(headers)).body.messages;
  expect(history.find((row: any) => row.metadata?.type === 'plan').metadata).toMatchObject({ resourceLabels: event.resourceLabels, replyToMessageId: accepted.messageId, requestId: 'fe03-sql-request' });
  expect(history.find((row: any) => row.id === accepted.messageId).metadata).toEqual({ requestId: 'fe03-sql-request' });
  await plans.updatePlanStatus(event.planId, 'completed');
  const restored = await request(app).get(`/api/conversations/${conv.id}/executions/latest`).set(headers);
  expect(restored.status).toBe(200); expect(restored.body.plan.resourceLabels).toEqual(event.resourceLabels);
  await pool.query(await readFile(new URL('../../../../db/v3/0006_fe03_resource_labels.sql', import.meta.url), 'utf8'));
  expect((await plans.getPlan(event.planId))?.resource_labels).toEqual(event.resourceLabels);
});
